# Generated by Django 3.2.5 on 2021-07-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='size',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='sku',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
