# Generated by Django 3.2.5 on 2021-07-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_auto_20210702_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='status',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line1',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line3',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Address Line 3'),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='address',
            name='fname',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Full Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='lname',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Last Name'),
        ),
    ]
